apiVersion: v1
kind: Service
metadata:
  name: gitlab-svc
spec:
  selector:
    app: gitlab
  ports:
  - protocol: "TCP"
    port: 8888
    targetPort: 80
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ee:latest
          ports:
            - containerPort: 443
            - containerPort: 80
          volumeMounts:
            - name: config-vol
              mountPath: /etc/config
            - name: logs-vol
              mountPath: /var/log/gitlab
            - name: data-vol
              mountPath: /var/opt/gitlab
      volumes:
        - name: config-vol
          hostPath:
            path: /srv/gitlab/config
        - name: logs-vol
          hostPath:
            path: /srv/gitlab/logs
        - name: data-vol
          hostPath:
            path: /srv/gitlab/data