apiVersion: apps/v1
kind: Deployment
metadata:
  name: playground-v1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: playground-v1
  template:
    metadata:
      labels:
        app: playground-v1
    spec:
      containers:
      - image: wil42/playground:v1
        name: payground-v1
        ports:
        - containerPort: 80
