apiVersion: v1
kind: Service
metadata:
  name: playground-service
  labels:
    app: playground-service
spec:
  type: NodePort
  ports:
  - name: 8888-8888
    nodePort: 31888
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: playground
